package drago

func A(props Props, children ...Node) Node          { return New("a", props, children...) }
func Abbr(props Props, children ...Node) Node       { return New("abbr", props, children...) }
func Address(props Props, children ...Node) Node    { return New("address", props, children...) }
func Area(props Props, children ...Node) Node       { return New("area", props, children...) }
func Article(props Props, children ...Node) Node    { return New("article", props, children...) }
func Aside(props Props, children ...Node) Node      { return New("aside", props, children...) }
func Audio(props Props, children ...Node) Node      { return New("audio", props, children...) }
func B(props Props, children ...Node) Node          { return New("b", props, children...) }
func Base(props Props, children ...Node) Node       { return New("base", props, children...) }
func Bdi(props Props, children ...Node) Node        { return New("bdi", props, children...) }
func Bdo(props Props, children ...Node) Node        { return New("bdo", props, children...) }
func Blockquote(props Props, children ...Node) Node { return New("blockquote", props, children...) }
func Body(props Props, children ...Node) Node       { return New("body", props, children...) }
func Br(props Props, children ...Node) Node         { return New("br", props, children...) }
func Button(props Props, children ...Node) Node     { return New("button", props, children...) }
func Canvas(props Props, children ...Node) Node     { return New("canvas", props, children...) }
func Caption(props Props, children ...Node) Node    { return New("caption", props, children...) }
func Cite(props Props, children ...Node) Node       { return New("cite", props, children...) }
func Code(props Props, children ...Node) Node       { return New("code", props, children...) }
func Col(props Props, children ...Node) Node        { return New("col", props, children...) }
func Colgroup(props Props, children ...Node) Node   { return New("colgroup", props, children...) }
func Data(props Props, children ...Node) Node       { return New("data", props, children...) }
func Datalist(props Props, children ...Node) Node   { return New("datalist", props, children...) }
func Dd(props Props, children ...Node) Node         { return New("dd", props, children...) }
func Del(props Props, children ...Node) Node        { return New("del", props, children...) }
func Details(props Props, children ...Node) Node    { return New("details", props, children...) }
func Dfn(props Props, children ...Node) Node        { return New("dfn", props, children...) }
func Dialog(props Props, children ...Node) Node     { return New("dialog", props, children...) }
func Div(props Props, children ...Node) Node        { return New("div", props, children...) }
func Dl(props Props, children ...Node) Node         { return New("dl", props, children...) }
func Dt(props Props, children ...Node) Node         { return New("dt", props, children...) }
func Em(props Props, children ...Node) Node         { return New("em", props, children...) }
func Embed(props Props, children ...Node) Node      { return New("embed", props, children...) }
func Fieldset(props Props, children ...Node) Node   { return New("fieldset", props, children...) }
func Figcaption(props Props, children ...Node) Node { return New("figcaption", props, children...) }
func Figure(props Props, children ...Node) Node     { return New("figure", props, children...) }
func Footer(props Props, children ...Node) Node     { return New("footer", props, children...) }
func Form(props Props, children ...Node) Node       { return New("form", props, children...) }
func H1(props Props, children ...Node) Node         { return New("h1", props, children...) }
func H2(props Props, children ...Node) Node         { return New("h2", props, children...) }
func H3(props Props, children ...Node) Node         { return New("h3", props, children...) }
func H4(props Props, children ...Node) Node         { return New("h4", props, children...) }
func H5(props Props, children ...Node) Node         { return New("h5", props, children...) }
func H6(props Props, children ...Node) Node         { return New("h6", props, children...) }
func Head(props Props, children ...Node) Node       { return New("head", props, children...) }
func Header(props Props, children ...Node) Node     { return New("header", props, children...) }
func Hgroup(props Props, children ...Node) Node     { return New("hgroup", props, children...) }
func Hr(props Props, children ...Node) Node         { return New("hr", props, children...) }
func Html(props Props, children ...Node) Node       { return New("html", props, children...) }
func I(props Props, children ...Node) Node          { return New("i", props, children...) }
func Iframe(props Props, children ...Node) Node     { return New("iframe", props, children...) }
func Img(props Props, children ...Node) Node        { return New("img", props, children...) }
func Input(props Props, children ...Node) Node      { return New("input", props, children...) }
func Ins(props Props, children ...Node) Node        { return New("ins", props, children...) }
func Kbd(props Props, children ...Node) Node        { return New("kbd", props, children...) }
func Keygen(props Props, children ...Node) Node     { return New("keygen", props, children...) }
func Label(props Props, children ...Node) Node      { return New("label", props, children...) }
func Legend(props Props, children ...Node) Node     { return New("legend", props, children...) }
func Li(props Props, children ...Node) Node         { return New("li", props, children...) }
func Link(props Props, children ...Node) Node       { return New("link", props, children...) }
func Main(props Props, children ...Node) Node       { return New("main", props, children...) }
func Map(props Props, children ...Node) Node        { return New("map", props, children...) }
func Mark(props Props, children ...Node) Node       { return New("mark", props, children...) }
func Math(props Props, children ...Node) Node       { return New("math", props, children...) }
func Menu(props Props, children ...Node) Node       { return New("menu", props, children...) }
func Menuitem(props Props, children ...Node) Node   { return New("menuitem", props, children...) }
func Meta(props Props, children ...Node) Node       { return New("meta", props, children...) }
func Meter(props Props, children ...Node) Node      { return New("meter", props, children...) }
func Nav(props Props, children ...Node) Node        { return New("nav", props, children...) }
func Noscript(props Props, children ...Node) Node   { return New("noscript", props, children...) }
func Object(props Props, children ...Node) Node     { return New("object", props, children...) }
func Ol(props Props, children ...Node) Node         { return New("ol", props, children...) }
func Optgroup(props Props, children ...Node) Node   { return New("optgroup", props, children...) }
func Option(props Props, children ...Node) Node     { return New("option", props, children...) }
func Output(props Props, children ...Node) Node     { return New("output", props, children...) }
func P(props Props, children ...Node) Node          { return New("p", props, children...) }
func Param(props Props, children ...Node) Node      { return New("param", props, children...) }
func Picture(props Props, children ...Node) Node    { return New("picture", props, children...) }
func Pre(props Props, children ...Node) Node        { return New("pre", props, children...) }
func Progress(props Props, children ...Node) Node   { return New("progress", props, children...) }
func Q(props Props, children ...Node) Node          { return New("q", props, children...) }
func Rb(props Props, children ...Node) Node         { return New("rb", props, children...) }
func Rp(props Props, children ...Node) Node         { return New("rp", props, children...) }
func Rt(props Props, children ...Node) Node         { return New("rt", props, children...) }
func Rtc(props Props, children ...Node) Node        { return New("rtc", props, children...) }
func Ruby(props Props, children ...Node) Node       { return New("ruby", props, children...) }
func S(props Props, children ...Node) Node          { return New("s", props, children...) }
func Samp(props Props, children ...Node) Node       { return New("samp", props, children...) }
func Script(props Props, children ...Node) Node     { return New("script", props, children...) }
func Section(props Props, children ...Node) Node    { return New("section", props, children...) }
func Select(props Props, children ...Node) Node     { return New("select", props, children...) }
func Slot(props Props, children ...Node) Node       { return New("slot", props, children...) }
func Small(props Props, children ...Node) Node      { return New("small", props, children...) }
func Source(props Props, children ...Node) Node     { return New("source", props, children...) }
func Span(props Props, children ...Node) Node       { return New("span", props, children...) }
func Strong(props Props, children ...Node) Node     { return New("strong", props, children...) }
func Style(props Props, children ...Node) Node      { return New("style", props, children...) }
func Sub(props Props, children ...Node) Node        { return New("sub", props, children...) }
func Summary(props Props, children ...Node) Node    { return New("summary", props, children...) }
func Sup(props Props, children ...Node) Node        { return New("sup", props, children...) }
func Svg(props Props, children ...Node) Node        { return New("svg", props, children...) }
func Table(props Props, children ...Node) Node      { return New("table", props, children...) }
func Tbody(props Props, children ...Node) Node      { return New("tbody", props, children...) }
func Td(props Props, children ...Node) Node         { return New("td", props, children...) }
func Template(props Props, children ...Node) Node   { return New("template", props, children...) }
func Textarea(props Props, children ...Node) Node   { return New("textarea", props, children...) }
func Tfoot(props Props, children ...Node) Node      { return New("tfoot", props, children...) }
func Th(props Props, children ...Node) Node         { return New("th", props, children...) }
func Thead(props Props, children ...Node) Node      { return New("thead", props, children...) }
func Time(props Props, children ...Node) Node       { return New("time", props, children...) }
func Title(props Props, children ...Node) Node      { return New("title", props, children...) }
func Tr(props Props, children ...Node) Node         { return New("tr", props, children...) }
func Track(props Props, children ...Node) Node      { return New("track", props, children...) }
func U(props Props, children ...Node) Node          { return New("u", props, children...) }
func Ul(props Props, children ...Node) Node         { return New("ul", props, children...) }
func Var(props Props, children ...Node) Node        { return New("var", props, children...) }
func Video(props Props, children ...Node) Node      { return New("video", props, children...) }
func Wbr(props Props, children ...Node) Node        { return New("wbr", props, children...) }
